/**
 * /src/utils/export.ts
 * PURE HELPERS
 *
 * Human-readable
 * Mechanic-friendly
 * Stable keys
 */

import type { DiagnosticResult } from "../models/diagnosticResult";
import type { ObservationResponse } from "../core/observations";
import type { Vehicle } from "../models/vehicle";
import { HYPOTHESIS_FAMILY_LABELS, type HypothesisFamilyId } from "../diagnostics/hypothesisFamilies";
import { OBSERVATION_DEFINITIONS, type ObservationId } from "../core/observations";

function getHypothesisLabel(id: string | null): string {
  if (!id) return "No hypothesis";
  if (id === "SAFETY_OVERRIDE") return "Safety Override Active";
  return HYPOTHESIS_FAMILY_LABELS[id as HypothesisFamilyId] ?? id;
}

function getObservationLabel(id: string): string {
  const def = OBSERVATION_DEFINITIONS[id as ObservationId];
  return def?.label ?? id;
}

function getConfidenceLabel(confidence: number): string {
  if (confidence >= 0.8) return "High";
  if (confidence >= 0.5) return "Medium";
  if (confidence >= 0.3) return "Low";
  return "Very Low";
}

export type ExportPayload = {
  result: DiagnosticResult;
  vehicle?: Vehicle | null;
  observations?: ObservationResponse[];
  userNotes?: string;
  scores?: Record<string, number>;
};

/**
 * Export diagnostic result as human-readable text
 */
export function exportDiagnosticResult(payload: ExportPayload): string {
  const { result, vehicle, observations, userNotes, scores } = payload;
  
  const lines: string[] = [];
  
  lines.push("═══════════════════════════════════════════════════════════");
  lines.push("                    CAR DIAGNOSTICS REPORT");
  lines.push("═══════════════════════════════════════════════════════════");
  lines.push("");
  
  // Vehicle info
  if (vehicle) {
    lines.push("VEHICLE:");
    lines.push(`  Name: ${vehicle.name}`);
    lines.push(`  Make/Model: ${vehicle.year ? `${vehicle.year} ` : ""}${vehicle.make} ${vehicle.model}`);
    if (vehicle.currentMileage > 0) {
      lines.push(`  Mileage: ${vehicle.currentMileage.toLocaleString()} miles`);
    }
    lines.push("");
  }
  
  // Diagnostic result
  lines.push("DIAGNOSIS:");
  lines.push(`  Date: ${new Date(result.timestamp).toLocaleString()}`);
  lines.push(`  Entry Point: ${result.entryAnchor}`);
  lines.push(`  Top Hypothesis: ${getHypothesisLabel(result.topHypothesis)}`);
  lines.push(`  Confidence: ${getConfidenceLabel(result.confidence)} (${Math.round(result.confidence * 100)}%)`);
  lines.push("");
  
  // Supporting observations
  if (result.supportingObservations && result.supportingObservations.length > 0) {
    lines.push("SUPPORTING OBSERVATIONS:");
    result.supportingObservations.forEach((obsId) => {
      lines.push(`  • ${getObservationLabel(obsId)}`);
    });
    lines.push("");
  }
  
  // All observations
  if (observations && observations.length > 0) {
    lines.push("ALL RECORDED OBSERVATIONS:");
    observations.forEach((obs) => {
      const label = getObservationLabel(obs.id);
      const response = obs.value === "YES" ? "✓ YES" : obs.value === "NO" ? "✗ NO" : "? UNSURE/SKIP";
      lines.push(`  ${response} - ${label}`);
    });
    lines.push("");
  }
  
  // Other scores
  if (scores && Object.keys(scores).length > 1) {
    lines.push("OTHER POSSIBILITIES:");
    Object.entries(scores)
      .filter(([family]) => family !== result.topHypothesis)
      .sort((a, b) => Math.abs(b[1]) - Math.abs(a[1]))
      .slice(0, 4)
      .forEach(([family, score]) => {
        lines.push(`  • ${getHypothesisLabel(family)}: Score ${score.toFixed(1)}`);
      });
    lines.push("");
  }
  
  // Safety notes
  if (result.safetyNotes && result.safetyNotes.length > 0) {
    lines.push("⚠️ SAFETY NOTES:");
    result.safetyNotes.forEach((note) => {
      lines.push(`  • ${note}`);
    });
    lines.push("");
  }
  
  // User notes
  if (userNotes && userNotes.trim()) {
    lines.push("USER NOTES:");
    lines.push(`  ${userNotes}`);
    lines.push("");
  }
  
  lines.push("───────────────────────────────────────────────────────────");
  lines.push(`Result ID: ${result.id}`);
  lines.push("Generated by Car Diagnostics App");
  lines.push("═══════════════════════════════════════════════════════════");
  
  return lines.join("\n");
}

/**
 * Export diagnostic result as JSON (for developer feedback)
 */
export function exportDiagnosticResultJSON(payload: ExportPayload): string {
  return JSON.stringify({
    version: "1.0",
    exportedAt: new Date().toISOString(),
    result: payload.result,
    vehicle: payload.vehicle ?? null,
    observations: payload.observations ?? [],
    userNotes: payload.userNotes ?? "",
    scores: payload.scores ?? {},
  }, null, 2);
}

/**
 * Download content as a file
 */
export function downloadAsFile(content: string, filename: string, mimeType: string = "text/plain"): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Copy content to clipboard
 */
export async function copyToClipboard(content: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(content);
    return true;
  } catch {
    return false;
  }
}
